

services:
  mongo:
    image: mongo:6.0
    user: root
    entrypoint: |
      bash -c 'set -e
      mkdir -p /etc/mongo
      if [ ! -f /etc/mongo/keyfile ]; then
        openssl rand -base64 756 > /etc/mongo/keyfile
      fi
      chown 999:999 /etc/mongo/keyfile
      chmod 400 /etc/mongo/keyfile
      exec /usr/local/bin/docker-entrypoint.sh \
           mongod --replSet rs0 --bind_ip_all --keyFile /etc/mongo/keyfile'
    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: 1111
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./libs/database/init.js:/docker-entrypoint-initdb.d/init.js:ro
      - mongo_key:/etc/mongo

  auth:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
    env_file: apps/auth/.env
    ports:
      - "3001:3001"
    depends_on:
      - mongo
      - redis

  event:
      build:
        context: .
        dockerfile: apps/event/Dockerfile
      env_file: apps/event/.env
      ports:
        - "3002:3002"
      depends_on:
        - mongo

  gateway:
      build:
        context: .
        dockerfile: apps/gateway/Dockerfile
      environment:
        AUTH_URL: http://auth:3000
        EVENT_URL: http://event:3000
      env_file: apps/gateway/.env
      ports:
        - "3000:3000"
      depends_on:
        - auth
        - event
        - redis
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --appendonly yes
volumes:
  mongo_data:
  mongo_key: