

services:
  mongo:
    image: mongo:6.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1111
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./libs/database/init.js:/docker-entrypoint-initdb.d/init.js:ro

  auth:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
    env_file: apps/auth/.env
    ports:
      - "3001:3001"
    depends_on:
      - mongo

  event:
      build:
        context: .
        dockerfile: apps/event/Dockerfile
      env_file: apps/event/.env
      ports:
        - "3002:3002"
      depends_on:
        - mongo

  gateway:
      build:
        context: .
        dockerfile: apps/gateway/Dockerfile
      environment:
        AUTH_URL: http://auth:3000
        EVENT_URL: http://event:3000
      env_file: apps/gateway/.env
      ports:
        - "3000:3000"
      depends_on:
        - auth
        - event

volumes:
  mongo_data: